version = 0.1

[default.global.parameters]
profile = "javelin"
region = "us-east-1"

[default.build.parameters]
template_file = "template-dev.yaml"

[default.deploy.parameters]
stack_name = "formula-helper-dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
